# Generated by Django 2.2.3 on 2019-09-02 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='regularincomedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('Description', models.CharField(max_length=25)),
                ('Amount', models.FloatField(default=0)),
                ('Frequency', models.CharField(max_length=15)),
                ('Start_Date', models.DateField(null=True)),
                ('End_Date', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='regularexpenseddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('Description', models.CharField(max_length=25)),
                ('Amount', models.FloatField(default=0)),
                ('Frequency', models.CharField(max_length=15)),
                ('Start_Date', models.DateField(null=True)),
                ('End_Date', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='lumpsumincome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('Description', models.CharField(max_length=25)),
                ('Amount', models.FloatField(default=0)),
                ('When_Injecting', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='lumpsumexpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('Description', models.CharField(max_length=25)),
                ('Amount', models.FloatField(default=0)),
                ('When_Expended', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='inputdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('Property_Value', models.FloatField(default=0)),
                ('Start_Month_of_Tool', models.CharField(max_length=15)),
                ('Start_Year_of_Tool', models.IntegerField(default=0)),
                ('Amount_Owed_As_of_Start_of_Tool', models.FloatField(default=0)),
                ('Current_Payment_for_Loan', models.FloatField(default=0)),
                ('Frequency_of_Payment', models.CharField(max_length=15)),
                ('Current_Interest_rate', models.FloatField(default=0)),
                ('Terms_of_Rate', models.IntegerField(default=0)),
                ('APPROVED_AMOUNT', models.FloatField(default=0)),
                ('CURRENT_OWED_ON_HELOC', models.FloatField(default=0)),
                ('PROJECTED_INJECTION_TO_MORTGAGE', models.FloatField(default=0)),
                ('RECURRING_INJECTION_AFTER_HELOC_REACHES_ZERO', models.FloatField(default=0)),
                ('HELOC_INITIAL_INTEREST_RATE', models.FloatField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='currentdebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('Type', models.CharField(max_length=25)),
                ('Owed', models.FloatField(default=0)),
                ('As_Of', models.DateField(null=True)),
                ('Payment', models.FloatField(default=0)),
                ('Rate', models.FloatField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
