# Generated by Django 2.2.3 on 2019-09-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='Terms_of_Rate',
            field=models.IntegerField(default=30),
        ),
    ]
